// <auto-generated />
namespace Travel_TripProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class update_Comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Comment));
        
        string IMigrationMetadata.Id
        {
            get { return "202501032002451_update_Comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
